language: go

go:
  - "1.11.x"
  - master

# Force-enable Go modules. Also force go to use the code in vendor/
# These will both be unnecessary when Go 1.13 lands.
env:
  global:
    - secure: "amQu8v8+HqjCI2EbT7ecxcuadZHi6ecO4Nz3OVHen0JqfsazUz1eXIOB+0vdkTyDPJ7Sk5MnXKKIl3rQRrNg1EK+xsNmw4muGwiHRt5RaZhx0xmwxagdavnwsS4Ka4pTnbI5MXgnCkabOUYoA6dgkPSqdQXazkB2OPHmRXzzgu4uwT9u34WOOVqqqBBvnEqsfBQVjYSRva9UxQIB3Iu8yo0/JXON1OZ0Qm2bIFbz2B8pJuJWJFpLuIZqPwG3N0m8fqOOSzZnQ98RUDUPPY+1vEybtEYcVqF3kwfJLoXZyoRitSmjrKNCkMwvJ/QmrQFY8YOM2v5pI8fOsMbfMF0zsXo3PFxuEEpyigwpySb21OYsnARz6vHgUYfzPucvjB4wqxcPsay0oA1U1SrBlr8Cprk9kclo7HUEjx0v1qFqgkDGWRXUQEJMYGEqgBYgs79khoON+p2p/v4EEmqbPpzN6BBPqjM9/vnYRJ6XTQCAXRtK62FnNnDn/QyE3x0wIVcamDmHgpbLVhvWcyOERRLuT/lyjIRiqMvnl7mvfAOI8oHLPF7Wrz9grD0xJTOPFsH7RL4Y1jvQtLcC4n+5IIKxYTNaYyYU6lWZ0OSV6+Xa53SE93YhebjmWJvkTyPVqq1WR/kdCPQjtgGlQpYM6Djmx5oRYWKd9l1X1HhxyD7gYhs="
    - GO111MODULE=on

# Only clone the most recent commit.
git:
  depth: 1

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

# Don't email me the results of the test runs.
# https://docs.travis-ci.com/user/notifications/#configuring-slack-notifications
notifications:
  email: false
  # slack:
  #   on_success: always
  #   on_failure: never

before_script:
  - go get golang.org/x/lint/golint
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - ${GOPATH}/bin/golint ./...
  - go test -v -race -covermode=atomic -coverprofile=coverage.out ./... # Run all the tests with the race detector enabled
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

# before_deploy:
# deploy:
#   skip_cleanup: true
# after_deploy:
