language: go

go:
  - "1.11.x"
  - master

# Force-enable Go modules. Also force go to use the code in vendor/
# These will both be unnecessary when Go 1.13 lands.
env:
  global:
    - secure: gj0jKGPQZIapPNzwVorhI5NBjc9RXk7pUoTi5MfaMCYeqdXtnNz+6UZfphJ2Bg/q64gLTZhzOKd1YjEVsT3VhouiQ6qhjpAA5P+BTFHoBqwyfnGacmQleLD/94Tqzu6RNxYFo48QghfW6HGive2TwAFm/7PjHA41/QNOxgpYRRzP1bhnBzpsQf8pCMOc2GN/rd5YlioS3biwy8o90p13WZq+zFNR8LngySu67c6e1Z1RWzSozUl7CCAoO8eKQmKLSI9dfKjc6pFFEWtuuGG2iFw7yfow7fzHhJI7y0nRKgYjZCMi2vJF+OQn9Ct51Q5R1a4aIzxo3FN4/hgGhXIIGnLNSAIf4Ec9MKYuAjcK5+dx9e01+/rSDjRr0mljR5X0D2B+aW/pjsZLsbZn9ry+bMmjfDgM3kPI9wglztRMm3TL6vUKdqTGgRYkMgx3lMnOWBmvtzD6e/Jy5t7ALJLIRWWDIuh1ftzN4sSkuEK6HiyMZ8/bgRY6eBbCFlX4Y5mBZWtFT9kZsRBFhCALVSzKTDvJqNgnXUqr90WbJbmc7ibsJIo+uh/PaPLZEQZd6fDTao6OWaVcDBR/rKR/fDBrCVGoQGqt8QISTpOWCClHaUg+Pgjsd145p7Jf7jTVVSpq0/g98hA9Zo0PAR5txfi7hgUJlJltMMIlxaWUmvkDLWw=
    - GO111MODULE=on

# Only clone the most recent commit.
git:
  depth: 1

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

# Don't email me the results of the test runs.
# https://docs.travis-ci.com/user/notifications/#configuring-slack-notifications
notifications:
  email: false
  # slack:
  #   on_success: always
  #   on_failure: never

before_script:
  - go get golang.org/x/lint/golint
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - ${GOPATH}/bin/golint ./...
  - go test -v -race -covermode=atomic -coverprofile=coverage.out ./... # Run all the tests with the race detector enabled
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

# before_deploy:
# deploy:
#   skip_cleanup: true
# after_deploy:
